version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing Terraform
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.9.0/terraform_0.9.0_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform -chdir=terraform init
  build:
    commands:
      - echo Applying Terraform configuration...
      - terraform -chdir=terraform apply -auto-approve

